# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_id', models.IntegerField()),
                ('taxi_reg_no', models.CharField(max_length=400)),
                ('taxi_name', models.CharField(max_length=200)),
                ('taxi_contact', models.IntegerField()),
                ('taxi_route', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('vehicle_reg_no', models.CharField(max_length=200)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_contact', models.IntegerField()),
                ('vehile_route', models.CharField(max_length=250)),
            ],
        ),
    ]
