# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20170425_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='occupancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vechile_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
