# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20170426_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bookings',
            field=models.IntegerField(default=0),
        ),
    ]
