# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vechile_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
