# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_vehicle_browse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='browse_image',
        ),
    ]
