# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_remove_vehicle_browse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Browse'),
        ),
    ]
