# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20170817_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='occupancy',
        ),
    ]
