# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SignupForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('pwd', models.CharField(max_length=200)),
                ('cpw', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('phone_no', models.IntegerField(default=0)),
            ],
        ),
    ]
